⚠️ CONFLICT! Lineage pull request for: skeleton
cisagov/gophish-docker pull request #53
Opened 2022-11-21 23:24 UTC by cisagovbot

# Lineage Pull Request: CONFLICT #

<img align="left" width="100" src="https://raw.githubusercontent.com/cisagov/action-lineage/develop/src/achtung.gif">

[Lineage] has created this pull request to incorporate new changes found in an
upstream repository:

Upstream repository: [`https://github.com/cisagov/skeleton-docker.git`](https://github.com/cisagov/skeleton-docker.git)
Remote branch: `HEAD`

Check the changes in this pull request to ensure they won't cause issues with
your project.

The `lineage/skeleton` branch has **one or more unresolved merge conflicts**
that you must resolve before merging this pull request!

## How to resolve the conflicts ##

1. Take ownership of this pull request by removing any other assignees.

1. Clone the repository locally, and reapply the merge:

    ```console
    git clone git@github.com:cisagov/gophish-docker.git gophish-docker
    cd gophish-docker
    git remote add skeleton https://github.com/cisagov/skeleton-docker.git
    git remote set-url --push skeleton no_push
    git switch develop
    git checkout -b lineage/skeleton --track origin/develop
    git pull skeleton HEAD
    git status
    ```

1. Review the changes displayed by the `status` command.  Fix any conflicts and
   possibly incorrect auto-merges.

1. After resolving each of the conflicts, `add` your changes to the
   branch, `commit`, and `push` your changes:

    ```console
    git add .github/dependabot.yml .pre-commit-config.yaml README.md bump_version.sh 
    git commit
    git push --force --set-upstream origin lineage/skeleton
    ```

    Note that you may *append* to the default merge commit message
    that git creates for you, but *please do not delete the existing
    content*.  It provides useful information about the merge that is
    being performed.

1. Wait for all the automated tests to pass.

1. Check the "Everything is cool" checkbox below:

    - [ ] ✌️ The conflicts in this pull request have been resolved.

1. Mark this draft pull request "Ready for review".

---

**Note:** *You are seeing this because one of this repository's maintainers has
configured [Lineage] to open pull requests.*

For more information:

🛠 [Lineage] configurations for this project are stored in `.github/lineage.yml`

📚 [Read more about Lineage][Lineage]

[//]: # (lineage:metadata:{&quot;slayed&quot;:true})
[Lineage]: https://github.com/cisagov/action-lineage/ "Lineage GitHub Action"

2022-11-23 21:42 UTC, jsf9k approved these changes

2022-11-28 16:33 UTC, dav3r approved these changes
🎣

2022-12-07 21:19 UTC, mcdonnnj requested changes

2022-12-07 21:19 UTC, mcdonnnj commented on Dockerfile
> +RUN rm -rf /var/lib/apt/lists/*
Since these are logically connected they should be one `RUN` command.

```suggestion
RUN apt-get --quiet --quiet clean \
    && rm -rf /var/lib/apt/lists/*
```

2022-12-07 21:19 UTC, mcdonnnj commented on Dockerfile
> +RUN apt-get remove --quiet --quiet $INSTALL_DEPS
I would just like to note that every time we do this we should be using a multi-stage build instead.

2022-12-07 21:19 UTC, mcdonnnj commented on Dockerfile
> +ARG GOPHISH_VERSION="0.11.0-cisa.1"
We only need to declare `ARG`s in this context if they are used in `FROM` commands.

```suggestion
```

2022-12-07 21:19 UTC, mcdonnnj commented on Dockerfile
> +ARG GOPHISH_VERSION
```suggestion
# The version of Gophish to install
ARG GOPHISH_VERSION="0.11.0-cisa.1"
```

2022-12-07 21:29 UTC, jsf9k commented on Dockerfile
> +RUN apt-get remove --quiet --quiet $INSTALL_DEPS
I'm just trying to resolve the Lineage conflicts in this PR.  I feel like changing this to a multi-stage build should be a separate PR.

2022-12-16 16:48 UTC, mcdonnnj approved these changes

2022-12-16 16:48 UTC, mcdonnnj commented on Dockerfile
> +    && ln -snf ${CISA_HOME}/data/gophish.db ${CISA_HOME}/gophish.db
```suggestion
    && ln --symbolic --no-dereference --force ${CISA_HOME}/data/gophish.db ${CISA_HOME}/gophish.db
```

2022-12-16 16:48 UTC, mcdonnnj commented on Dockerfile
> +    && rm -rf /var/lib/apt/lists/*
```suggestion
    && rm --recursive --force /var/lib/apt/lists/*
```

2022-12-16 16:48 UTC, mcdonnnj commented on Dockerfile
> +RUN chown -R ${CISA_USER}:${CISA_GROUP} ${CISA_HOME}
```suggestion
RUN chown --recursive ${CISA_USER}:${CISA_GROUP} ${CISA_HOME}
```

2022-12-16 17:52 UTC, merged